name: Playwright Tests
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      working-directory: ./App
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./App
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./App
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ./App/playwright-report/
        retention-days: 30
